### ISSUE TITLE
📚 3차 세미나 📚

### ISSUE THREAD

**Issue by laalaa31** [30th-THE-SOPT-Server-Part/SeoHee#4]
## 📌  Feature Issue
- 견고한 Node.js 프로젝트 설계
- User CRUD 구현(3차 세미나 실습)
- Blog CRUD 구현(3차 세미나 실습 폴더 내부에 Blog.ts Model을 만들고 CRUD 완성하기)

## 📝  To-do
✈ 실천과제(Level 1)
- [x] 3차 세미나에 나온 코드를 직접 타이핑하면서 익혀보기

🚀 발전과제(Level 2)
- [x] POST/blog
- [x] PUT/blog/:postId
- [x] GET/blog/:postId
- [x] DELETE/blog/:postId
