### ISSUE TITLE
📚 4차 세미나 📚

### ISSUE THREAD

**Issue by laalaa31** [30th-THE-SOPT-Server-Part/SeoHee#6]
## 📌  Feature Issue
- API 실습

## 📝  To-do
✈ 실천과제(Level 1)
- [x] 4차 세미나에서 나온 코드들 직접 타이핑하면서 익혀보기

🚀 발전과제(Level 2)
- [x] 3주차에 만들었던 user 생성 API에 express-validator 붙이기(isEmail() 처럼 다른 함수들 사용해보기)
- [x] 오늘 만든 Movie Collection CRUD API 만들기
